"use client";

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { DEMO_BANK, DEMO_WATERMARK } from "@/lib/constants";

const s = StyleSheet.create({
  page: { padding: 48, fontSize: 11, color: "#111", fontFamily: "Helvetica" },
  watermark: {
    position: "absolute", top: 320, left: 60, fontSize: 28, color: "#e5e5e5",
    transform: "rotate(-28deg)", fontFamily: "Helvetica-Bold",
  },
  brand: { fontSize: 18, fontFamily: "Helvetica-Bold", color: "#4f46e5" },
  sub: { fontSize: 9, color: "#666", marginTop: 2 },
  h1: { fontSize: 14, fontFamily: "Helvetica-Bold", marginTop: 24, marginBottom: 8 },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 5, borderBottom: "1px solid #eee" },
  label: { color: "#555" },
  val: { fontFamily: "Helvetica-Bold" },
  foot: { position: "absolute", bottom: 40, left: 48, right: 48, fontSize: 8, color: "#999", textAlign: "center", borderTop: "1px solid #eee", paddingTop: 8 },
});

function Header({ title }: { title: string }) {
  return (
    <View>
      <Text style={s.brand}>EduLoan</Text>
      <Text style={s.sub}>{DEMO_BANK}</Text>
      <Text style={s.h1}>{title}</Text>
    </View>
  );
}

function Line({ k, v }: { k: string; v: string }) {
  return (
    <View style={s.row}>
      <Text style={s.label}>{k}</Text>
      <Text style={s.val}>{v}</Text>
    </View>
  );
}

export function SanctionLetterPDF({ d }: { d: Record<string, string> }) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <Text style={s.watermark}>{DEMO_WATERMARK}</Text>
        <Header title="Loan Sanction Letter" />
        <Text style={{ marginBottom: 12, lineHeight: 1.5 }}>
          Dear {d.applicant},{"\n"}We are pleased to inform you that your educational
          loan application has been approved under the following terms.
        </Text>
        <Line k="Sanction reference" v={d.ref} />
        <Line k="Applicant" v={d.applicant} />
        <Line k="Course" v={d.course} />
        <Line k="Sanctioned amount" v={d.principal} />
        <Line k="Interest rate (p.a.)" v={d.rate} />
        <Line k="Tenure" v={d.tenure} />
        <Line k="Monthly EMI" v={d.emi} />
        <Line k="Total payable" v={d.total} />
        <Line k="Date of issue" v={d.date} />
        <Text style={{ marginTop: 20, lineHeight: 1.5, color: "#444" }}>
          This sanction is subject to the terms of the demonstration loan agreement.
          Funds, figures, and references herein are simulated for illustrative purposes.
        </Text>
        <Text style={s.foot}>{DEMO_WATERMARK} · Auto-generated by EduLoan</Text>
      </Page>
    </Document>
  );
}

export function ReceiptPDF({ d }: { d: Record<string, string> }) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <Text style={s.watermark}>{DEMO_WATERMARK}</Text>
        <Header title="EMI Payment Receipt" />
        <Line k="Transaction reference" v={d.txn} />
        <Line k="Applicant" v={d.applicant} />
        <Line k="Loan reference" v={d.ref} />
        <Line k="Installment no." v={d.installment} />
        <Line k="Amount paid" v={d.amount} />
        <Line k="Payment date" v={d.date} />
        <Line k="Status" v="SUCCESS (simulated)" />
        <Text style={{ marginTop: 20, color: "#444" }}>
          Thank you for your payment. This is a simulated receipt with no monetary value.
        </Text>
        <Text style={s.foot}>{DEMO_WATERMARK} · Auto-generated by EduLoan</Text>
      </Page>
    </Document>
  );
}
